/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/ZombieMan.glb -s 
*/
/* eslint-disable react/no-unknown-property */
/* eslint-disable react/prop-types */
import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useSkinnedMeshClone } from './SkinnedMeshClone'
import { useFrame } from '@react-three/fiber'

export function ZombieMan(props) {
  const group = useRef()

  // Custom hook useSkinnedMeshClone allows a skinnedMesh with primitives to be reused. Without out this only one mesh will be displayed
  const {scene, materials, animations, nodes} = useSkinnedMeshClone("/ZombieMan.glb")
  const { actions } = useAnimations(animations, group)
  //console.log(actions)
  //console.log(nodes)

  // Change animation
  const animation = useRef(props.animName.current)
  useFrame( (state, delta) => {
    //console.log(props.animName.current, animation.current)
    if (animation.current != props.animName.current) {
      actions[animation.current].fadeOut(0.5)
      actions[props.animName.current].reset().fadeIn(0.5).play()
      animation.current = (props.animName.current)
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <skinnedMesh 
            name="Adam" 
            geometry={nodes.Adam.geometry} 
            material={materials["Skin.Adam"]} 
            skeleton={nodes.Adam.skeleton} 
            castShadow
            receiveShadow
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ZombieMan.glb')
